#!/bin/dash
# usage: turnip-submit <assignment> <zid> <filename>

assignment="$1"
zid="$2"
filename="$3"

if ! test -d .turnip
then
    echo "turnip-submit: turnip directory .turnip not found" >&2
    exit 1
fi

if test "$#" -ne 3
then
    echo "usage: turnip-submit <assignment> <zid> <filename>" >&2
    exit 1
fi

if ! echo "$assignment" | grep -Eq '^[a-z][a-zA-Z0-9_]*$'
then
    echo "turnip-submit: invalid assignment: $assignment" >&2
    exit 1
fi

if ! echo "$zid" | grep -Eq '^z[0-9]{7}$'
then
    echo "turnip-submit: invalid zid: $zid" >&2
    exit 1
fi

if ! echo "$filename" | grep -Eq '^[a-zA-Z0-9_./-]+$'
then
    echo "turnip-submit: invalid filename: $filename" >&2
    exit 1
fi

if ! test -d ".turnip/$assignment"
then
    echo "turnip-submit: assignment $assignment not found" >&2
    exit 1
fi

if ! test -f "$filename"
then
    echo "turnip-submit: $filename: No such file or directory" >&2
    exit 1
fi

dir=".turnip/$assignment/submission/$zid"

mkdir -p "$dir"
i=$(ls "$dir" 2>/dev/null | wc -l | tr -d ' ')
i=$((i+1))
mkdir "$dir/$i"

cp "$filename" "$dir/$i/file"
basename "$filename" > "$dir/$i/name"
wc -c < "$filename" | tr -d ' ' > "$dir/$i/size"
date "+%a %b %e %H:%M:%S %Y" > "$dir/$i/date"

name=$(cat "$dir/$i/name")
size=$(cat "$dir/$i/size")
date=$(cat "$dir/$i/date")

echo "Submission accepted - submission $i: $name $size bytes @ $date"
